const GAME_CONFIG = {
  GAME_WIDTH: 1000,
  GAME_HEIGHT: 600,
  BACKGROUND_HEIGHT: 50,
  MIN_POWER: 100,
  MAX_POWER: 300,
  MIN_ANGLE: -1,
  MAX_ANGLE: -89,
  G: 9.81,
  IMPULSE_LOSS_RATIO: 0.75,
  SCALE: 2
};

GAME_CONFIG.WALL_HEIGHT = GAME_CONFIG.GAME_HEIGHT - GAME_CONFIG.BACKGROUND_HEIGHT - 150;
GAME_CONFIG.WALL_WIDTH = 150;

export {GAME_CONFIG};
